-- ACCESSORIES table
ALTER TABLE ACCESSORIES 
ADD CONSTRAINT FK_ACCESSORY_GROUP_ID FOREIGN KEY (accessory_group_id) REFERENCES ACCESSORY_GROUPS(id);
GO

-- IMPORT_INVOICES table
ALTER TABLE IMPORT_INVOICES
ADD CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(id);
GO

-- SALES_INVOICES table
ALTER TABLE SALES_INVOICES 
ADD CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id);
GO
ALTER TABLE SALES_INVOICES
ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(id);
GO

-- ACCESSORIES_IN_AN_IMPORT_INVOICE table
ALTER TABLE ACCESSORIES_IN_AN_IMPORT_INVOICE
ADD CONSTRAINT FK_IMPORT_INVOICE_ID FOREIGN KEY (import_invoice_id) REFERENCES IMPORT_INVOICES(id);
GO
ALTER TABLE ACCESSORIES_IN_AN_IMPORT_INVOICE
ADD CONSTRAINT FK_ACCESSORY_ID_IMPORT FOREIGN KEY (accessory_id) REFERENCES ACCESSORIES(id);
GO

-- ACCESSORIES_IN_A_SALES_INVOICE table
ALTER TABLE ACCESSORIES_IN_A_SALES_INVOICE
ADD CONSTRAINT FK_SALES_INVOICE_ID FOREIGN KEY (sales_invoice_id) REFERENCES SALES_INVOICES(id);
GO
ALTER TABLE ACCESSORIES_IN_A_SALES_INVOICE
ADD CONSTRAINT FK_ACCESSORY_ID_SALES FOREIGN KEY (accessory_id) REFERENCES ACCESSORIES(id);
GO